#!/usr/bin/env python3
from numpy.core.numeric import NaN
import rospy
from geometry_msgs.msg import Twist, Vector3
from sensor_msgs.msg import LaserScan
import numpy as np
import tensorflow as tf
import kerasncp as kncp
from kerasncp.tf import LTCCell


path = '/home/laiy/gitrepos/cyber/ws/src/Jackal_NCP/rosbag/model/model_angular'
model_angular = tf.keras.models.load_model(path)
path = '/home/laiy/gitrepos/cyber/ws/src/Jackal_NCP/rosbag/model/model_linear'
model_linear = tf.keras.models.load_model(path)

class Handler: 
    def __init__(self):
        self.angularz = []
        self.linearx = []
        self.cmd_pub = rospy.Publisher("/cmd_vel", Twist, queue_size = 10)
        self.scan_sub = rospy.Subscriber("/front/scan", LaserScan, self.scan_callback)

        print("INIT COMPLETE")


    def scan_callback(self, data):
        # print("data.ranges ", np.shape(data.ranges))
        ranges = np.transpose(np.asarray([data.ranges])).astype(np.float32)
        # print("ranges ", np.shape(ranges))
        input = np.array([[ranges]])
        # print("input ", np.shape(input))
        pred_ang = model_angular(input).numpy()
        pred_linear = model_linear(input).numpy()
        # print("pred = ", pred)
        self.angularz = pred_ang[0][0][0]
        self.linearx = pred_linear[0][0][0]
        if np.isnan(self.angularz): self.angularz = 0
        if np.isnan(self.linearx): self.linearx = 0
        print("pred = ", self. linearx, " ", self.angularz)
        self.cmd_pub.publish(Twist(linear = Vector3(x = self.linearx, y = 0.0, z = 0.0), angular = Vector3(x = 0, y = 0, z = self.angularz)))




def main():
    rospy.init_node('load_model', anonymous = True)
    handler = Handler()
    rospy.spin()


if __name__=='__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass