#!/usr/bin/env python3
import rospy
from geometry_msgs.msg import Twist, Vector3, TwistWithCovariance
from sensor_msgs.msg import LaserScan
import numpy as np
import csv


csvwriter = None

cmd = []

def cmd_callback(data):
    cmd = data.angular.z
    

def scan_callback(data):
    print(cmd)
    if (cmd):
        scan = data.ranges
        csvwriter.writerows([*scan, cmd])

## join_state publisher
cmd_sub = rospy.Subscriber("cmd_vel", Twist, cmd_callback)
scan_sub = rospy.Subscriber("front/scan", LaserScan, scan_callback)

filename = "data.csv"











def main():
    '''
    main 

    '''
    rospy.init_node('read_data', anonymous = True)

    with open(filename, 'w') as csvfile:
        csvwriter = csv.writer(csvfile)


    

    
    rospy.spin()

if __name__=='__main__':
    main()


