#!/usr/bin/env python3
import rospy
from geometry_msgs.msg import Twist, Vector3, TwistWithCovariance
from sensor_msgs.msg import LaserScan
import numpy as np
import csv

class Handler: 
    def __init__(self):
        self.csvwriter = None
        self.cmd = None
        self.cmd_sub = rospy.Subscriber("/cmd_vel", Twist, self.cmd_callback)
        self.scan_sub = rospy.Subscriber("/front/scan", LaserScan, self.scan_callback)

        with open("data.csv", 'w') as self.csvfile:
            print("open file")
            self.csvwriter = csv.writer(self.csvfile)


    def cmd_callback(self, data):
        self.cmd = data.angular.z
        print("cmd = ", self.cmd) 

    def scan_callback(self, data):
        if self.cmd:
            print("in scan ", np.shape(data.ranges))

            scan = data.ranges
            self.csvwriter.writerows([scan, self.cmd])


def main():
    '''
    main 

    '''
    rospy.init_node('read_data', anonymous = True)
    handler = Handler()
    rospy.spin()

if __name__=='__main__':
    main()


